### ISSUE TITLE
Using your Unraid Obico App, how does one configure dotenv.example if it doesn't exist?

### ISSUE THREAD

**Issue by superdong69** [imagegenius/docker-obico#13]
Trying to configure the Unraid Docker Application to send alerts via email. I've got everything else working lovely, but I can't figure out how to get alerts to work.

**Comment by hydazz** [comment]
you just copy the variables from the .env into extra variables in the template

**Comment by superdong69** [comment]
> you just copy the variables from the .env into extra variables in the template

I'm sorry,  what do you mean when you say extra variables in the template? You mean in the unraid variables when you edit the docker settings of the application?

**Comment by hydazz** [comment]
yes, within the template, at the bottom click `Add another Path, Port, Variable, Label or Device`, set `Config Type` to `Variable` and set the `Key` to the variable from the .env, eg `EMAIL_HOST`, repeat for any other variables from https://github.com/TheSpaghettiDetective/obico-server/blob/release/dotenv.example

**Comment by superdong69** [comment]
Yup, got that all sorted. Testing notifications just give me a server 500 error when configuring for SMTP Gmail. Followed all the instructions for using the google app password, and using the same account I use for unraid notifications which work fine.

**Comment by hydazz** [comment]
> notifications just give me a server 500 error when configuring for SMTP Gmail

please continue this issue here: https://github.com/imagegenius/docker-obico/issues/10

ill mark the variables issue closed :)
