### ISSUE TITLE
Fehler: failed to register layer: write /usr/lib/python3.7/site-packages/opencv_python_headless.libs/libvpx-e947aa05.so.8.0.1: no space left on device

### ISSUE THREAD

**Issue by Saltru62** [imagegenius/docker-obico#15]

**Comment by Saltru62** [comment]
Fehler: failed to register layer: write /usr/lib/python3.7/site-packages/opencv_python_headless.libs/libvpx-e947aa05.so.8.0.1: no space left on device

**Comment by hydazz** [comment]
`no space left on device` is your disk full? look in `df -h`
