### ISSUE TITLE
Unable to view webcam feeds through Obico mobile app

### ISSUE THREAD

**Issue by gabort-snow** [imagegenius/docker-obico#18]
I've linked the Obico iphone app to my printer and can view the feeds in the webpage but when I attempt to use the iPhone app, I'm seeing that no webcams are set up.
The logs indicate that something isn't available:

django.request WARNING  Not Found: /ent/api/personalized_mobile_ui/

Is this a result of the image being out of date compared to the official docker?

**Comment by hydazz** [comment]
possibly, ill try get the image updated soon

**Comment by gabort-snow** [comment]
Disregard. The issue was related to my credentials in Unraid for github. I wasn't pulling the latest images. All is working as expected.
