### ISSUE TITLE
471c0364-ig91 Error 500

### ISSUE THREAD

**Issue by gullygossner** [imagegenius/docker-obico#19]
Trying to run 471c0364-ig91 in docker (unraid). This occurs with both with docker compose and unraid's built in docker app method. 

It appears that everything loads fine but I when I attempt to access the site errors are thrown. 

I've attached a log file of the occurrence. 
[logfile.txt](https://github.com/user-attachments/files/16164631/logfile.txt)

**Comment by mericon** [comment]
Having the same exact problem

**Comment by Subcode** [comment]
same issue on a fresh install with the :latest tag.

**Comment by MVerBerkmoes** [comment]
Same issue here.  Have removed and reinstalled both Obico AND Redis with no joy.  I have almost an identical error log to the attachment included above.

UnRAID - v 6.12.11
Redis - v7.2.5

**Comment by TheBennyJ** [comment]
I'm also having the same issue

**Comment by TheBennyJ** [comment]
> I'm also having the same issue

Actually found my problem, I've setup it to point to a domain, when accessing from unraid it was trying to use the IP address instead. Going to the configured site URL solved my issue

**Comment by psybernoid** [comment]
I'm also having the same problem. Had to recreate my container recently. So starting with a new config. I'm getting the 500 error

**Comment by hydazz** [comment]
Obico keeps pushing breaking updates and its difficult to stay on top of them, Ill try get a working build up asap

**Comment by srsabu** [comment]
I was having the same problem but was able to use the instructions here to get access to Django.  I used the local IP address and port of my Unraid server as the domain.

https://stackoverflow.com/questions/16068518/django-site-matching-query-does-not-exist

**Comment by ss1gohan13** [comment]
Found a potential fix for anyone looking:

Follow these steps:

open unraid console
type:
docker exec -it 71c0df5a6061 /bin/bash
cd /app/obico/backend/
python3 manage.py shell

push enter

ip_address = '<your server ip>'

if not Site.objects.exists():
    Site.objects.create(domain=ip_address, name='My Site')
else:
    site = Site.objects.first()
    site.domain = ip_address
    site.name = 'My Site'
    site.save()
    
push enter a couple of time

restart obico

you should now be able to access the website

Thank you @IzFunk3

**Comment by gullygossner** [comment]
Attempting to do this fix. 

in the ip_adress line do I put my obico ip address and port number? Is there indentations required in the code to make it work propropely? 

I have attempted it a couple different ways but get IndentationError: expected an indented block after 'if' statement on line 3

and If I indent I get NameError: name 'Site' is not defined

**Comment by frmattb** [comment]
> Attempting to do this fix.
> 
> in the ip_adress line do I put my obico ip address and port number? Is there indentations required in the code to make it work propropely?
> 
> I have attempted it a couple different ways but get IndentationError: expected an indented block after 'if' statement on line 3
> 
> and If I indent I get NameError: name 'Site' is not defined

try this:

open unraid console for that docker
type:
cd /app/obico/backend/
python3 manage.py shell

push enter

ip_address = ''
from django.contrib.sites.models import Site

if not Site.objects.exists():
(add tab) Site.objects.create(domain=ip_address, name='My Site')
else:
(add tab) site = Site.objects.first()
site.domain = ip_address
site.name = 'My Site'
site.save()

**Comment by hydazz** [comment]
im unsure what exactly is causing this, this image is exactly the same as the upstream setup 😑

**Comment by hydazz** [comment]
Can you try repulling the latest image

**Comment by weawer** [comment]
i dont even seem to be able to access python3 in the docker.

**Comment by AstralDarko** [comment]
Same issue here.  No access to python3 by default.  Installed it, got the following error:

`Traceback (most recent call last):
  File "/app/obico/backend/manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/obico/backend/manage.py", line 10, in <module>
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?`

**Comment by hydazz** [comment]
believe youll need to invoke python with `python3.11`

still working on a fix, seems like every second build i do just works, then does not without making any changes so im loosing hair rn

**Comment by weawer** [comment]
thanks for your hard work and please dont stress too much about it!

**Comment by WoutvanderAa** [comment]
I am also running in this issue with django, does anyone know a fix for it?

**Comment by WoutvanderAa** [comment]
> Found a potential fix for anyone looking:
> 
> Follow these steps:
> 
> open unraid console type: docker exec -it 71c0df5a6061 /bin/bash cd /app/obico/backend/ python3 manage.py shell
> 
> push enter
> 
> ip_address = ''
> 
> if not Site.objects.exists(): Site.objects.create(domain=ip_address, name='My Site') else: site = Site.objects.first() site.domain = ip_address site.name = 'My Site' site.save()
> 
> push enter a couple of time
> 
> restart obico
> 
> you should now be able to access the website
> 
> Thank you @IzFunk3

I tried this but I got the following error message: Error response from daemon: No such container: 71c0df5a6061
bash: cd: /app/obico/backend/: No such file or directory
bash: python3: command not found

What am I doing wrong? do I not have python installed or something..

**Comment by jarjo** [comment]
you need to use the id of your container.

**Comment by WoutvanderAa** [comment]
> you need to use the id of your container.

I did that the second time and I got in, I tried the second command like the following; root@9fa07d551f9d:/# ip_address = '192.168.178.89:3334'

if not Site.objects.exists():
Site.objects.create(domain=ip_address, name='My Site')
else:
site = Site.objects.first()
site.domain = ip_address
site.name = 'My Site'
site.save()

And I got this error: bash: ip_address: command not found
bash: syntax error near unexpected token `('
bash: syntax error near unexpected token `domain=ip_address,'
bash: else:: command not found
bash: syntax error near unexpected token `('
bash: site.domain: command not found
bash: site.name: command not found

do you know what should I be doing differently to not get this error? I am very new to linux and docker in general.

**Comment by WhiskeySheppard** [comment]
I'm getting the same thing but I'm not using UnRAID. I attempted to install on Ubuntu/Docker and I cant get to the obico or the admin page. I keep getting Server 500 error. I've tried installing on two machines. 
[obico-server-web-1_logs.txt](https://github.com/user-attachments/files/16735358/obico-server-web-1_logs.txt)

**Comment by hydazz** [comment]
did this resolve the issue?
should note that error 500 is the 'intended' result if not accessing via `localhost`

https://www.obico.io/docs/server-guides/configure/#41-if-you-can-access-your-obico-server-using-httplocalhost3334

**Comment by gullygossner** [comment]
> did this resolve the issue? should note that error 500 is the 'intended' result if not accessing via `localhost`
> 
> https://www.obico.io/docs/server-guides/configure/#41-if-you-can-access-your-obico-server-using-httplocalhost3334

I think it's good to go. I had to manually add HOST_IP variable to my unraid template.

**Comment by weawer** [comment]
Seems to have resolved the issue thanks :)

**Comment by WhiskeySheppard** [comment]
Yea, I found a fix. It was due to poor documentation. 

![image](https://github.com/user-attachments/assets/ab61e356-9445-4f5c-9734-33832b3c7c12)

Step 4.2 fixed the issue. However when people typically follow a "guide" and they come to a issue, They dont typically look forward a few steps. They retrace the steps they've already done based on the guide to see what they may have overlooked. 

The guide is configuration through a Docker, How many docker instances are ran through a device where you can pull up a browser and view something through localhost? Most people run docker through a device they're accessing through SSH. 

SO to me, It would make more sense for this portion of the documentation:

![image](https://github.com/user-attachments/assets/a03c149d-7f42-41cc-b66f-f1a799c6d948)

should be listed prior to this: 

![image](https://github.com/user-attachments/assets/195d0fb5-0b96-4176-8995-c13b47f3e0e8)

Since in most cases, you wont be able to access or use (http://localhost:3334/admin/sites/site/). The typical user wont be able to access the obico homepage or the admin/djano page which they guide tells you to do once docker is up and running until they jump ahead in the documentation and follow the 4.2 step. Therefore this step should be listed in the documentation prior to telling you to test the obico homepage or the admin/djano page.

**Comment by AstralDarko** [comment]
> > did this resolve the issue? should note that error 500 is the 'intended' result if not accessing via `localhost`
> > https://www.obico.io/docs/server-guides/configure/#41-if-you-can-access-your-obico-server-using-httplocalhost3334
> 
> I think it's good to go. I had to manually add HOST_IP variable to my unraid template.

Same here.  After the update, manually adding the template variable resolved it.  Thanks so much for all your hard and fast work on this!

**Comment by frmattb** [comment]
> > did this resolve the issue? should note that error 500 is the 'intended' result if not accessing via `localhost`
> > https://www.obico.io/docs/server-guides/configure/#41-if-you-can-access-your-obico-server-using-httplocalhost3334
> 
> I think it's good to go. I had to manually add HOST_IP variable to my unraid template.

I'm not sure who setup the unraid template, but if we had a way of contacting them to get them to add the common variables to the template, it would help this whole operation a great deal.

**Comment by WoutvanderAa** [comment]
> > did this resolve the issue? should note that error 500 is the 'intended' result if not accessing via `localhost`
> > https://www.obico.io/docs/server-guides/configure/#41-if-you-can-access-your-obico-server-using-httplocalhost3334
> 
> I think it's good to go. I had to manually add HOST_IP variable to my unraid template.

It fixed it indeed sorry for the late reply

**Comment by MVerBerkmoes** [comment]
This did not resolve my issue, even after a full uninstall and reinstall on UnRAID.
