### ISSUE TITLE
No Host IP 

### ISSUE THREAD

**Issue by Offlinedsad** [imagegenius/docker-obico#23]
Hi, after a docker update I cant connect to the webui. The logs only say the below. I have redis installed and working but that doesn't seem to be helping much

Error: No Host IP has been specified in the 'HOST_IP' variable. Please set this variable to the domain/ip you access Obico from
For more information, see the README: https://github.com/imagegenius/docker-obico#variables

**Comment by Offlinedsad** [comment]
Hosting on unraid for context

**Comment by hydazz** [comment]
add another variable to the template called `HOST_IP`, and set it to the ip/domain you use to access the app
https://github.com/imagegenius/docker-obico?tab=readme-ov-file#parameters
it could be obico.example.com if using a reverse proxy, or just the ip of your unraid host
