### ISSUE TITLE
Error 500 -Cuda

### ISSUE THREAD

**Issue by Atom8832** [imagegenius/docker-obico#24]
I am unable to access the web UI, when attempting to do so I receive error 500. Platform is Unraid and I have everything otherwise set correctly I believe, have passed through GPU, created a HOST_IP entry etc, but still only ever get a 500 error. I imagine this is the same issue as was updated and fixed on the non-cuda branch, but it appears that there is no updated version of the cuda install, rolling back to a older install did seem to fix the issue. Thanks in advance for assistance

**Comment by hydazz** [comment]
give `ghcr.io/imagegenius/igpipepr-obico:cuda-version-471c0364` a shot, ill merge the change if all ok

**Comment by mezz64** [comment]
I was experiencing this same issue and using the image tag you suggested everything works as expected for me.

**Comment by hydazz** [comment]
the latest `:cuda` tag should have been updated with the changes from that PR
