### ISSUE TITLE
Error: No Redis URL has been specified in the

### ISSUE THREAD

**Issue by lwkalis** [imagegenius/docker-obico#5]
Unraid docker broken after update
Error: No Redis URL has been specified in the 'REDIS_URL' variable. (see https://github.com/imagegenius/docker-obico#redis)
![image](https://user-images.githubusercontent.com/124509299/216824169-e595fdc4-018a-4355-8c79-3e6a52dcc92b.png)

**Comment by hydazz** [comment]
add a new variable with the name `DOCKER_MODS` set it to `imagegenius/mods:universal-redis`. add another variable named `REDIS_URL` and set that to `redis://localhost:6379`.

Redis was removed in that update as most people already have a redis instance running to connect it to

**Comment by hydazz** [comment]
Success?

**Comment by lwkalis** [comment]
No. I’ve installed windows 10 and docker on a vm and still doesn’t work.

**Comment by hydazz** [comment]
What do you mean? Any errors?

**Comment by lwkalis** [comment]
[image: image.png]
this is where it gets stuck on both the VM and on unraid

**Comment by lwkalis** [comment]
It's solved now. The i didn't have the ip of the server setup in the
template
