### ISSUE TITLE
ModuleNotFoundError: No module named 'components'

### ISSUE THREAD

**Issue by jjbrunton** [imagegenius/docker-obico#8]
Upon installing this on Unraid, the container gets into a loop with:

ModuleNotFoundError: No module named 'components'

I have tried clearing the app data folder and recreating the container with the same result.

**Comment by hydazz** [comment]
please pin to `ghcr.io/imagegenius/obico:bd5410c9-ig27` until i get a chance to see whats causing this

**Comment by Burgess101** [comment]
Can confirm I am getting the same error.

**Comment by hydazz** [comment]
this has been fixed
